### ISSUE TITLE
Impossible to use the web installer under http proxy

### ISSUE THREAD

**Issue by dpeddi-gen** [smatechnologies/opcon-web-installer#1]
Good Morning,

Is impossible for us tu use this software behind our corporate proxy.

![image](https://user-images.githubusercontent.com/67015855/100983849-2c2e0e80-354a-11eb-9036-f5acc49f7ff6.png)

Here is the screenshot of the error.

Regards

Eddi

**Comment by ryandimick** [comment]
To access the product downloads from the web, the machine running this application needs access to the following:

smatechnologies.files.com - port 443
files.smatechnologies.com - port 990

If this is not an option, you may continue to reach out to Customer Support and they will give the ability to manually download new products.
